# Generated by Django 6.0.1 on 2026-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('physics_q', models.IntegerField()),
                ('physics_h', models.IntegerField()),
                ('physics_p', models.IntegerField()),
                ('maths_q', models.IntegerField()),
                ('maths_h', models.IntegerField()),
                ('maths_p', models.IntegerField()),
                ('chemistry_q', models.IntegerField()),
                ('chemistry_h', models.IntegerField()),
                ('chemistry_p', models.IntegerField()),
                ('english_q', models.IntegerField()),
                ('english_h', models.IntegerField()),
                ('english_p', models.IntegerField()),
                ('attendance', models.IntegerField()),
            ],
        ),
    ]
